name: dart_code_unused_linter
version: 1.0.0
description: Software analytics tool that helps developers analyse and improve software quality.

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=6.4.1 <7.0.0"
  analyzer_plugin: ">=0.11.3 <0.12.0"
  ansicolor: ^2.0.2
  args: ^2.5.0
  collection: ^1.18.0
  crypto: ^3.0.3
  file: ^7.0.0
  glob: ^2.1.2
  html: ">=0.15.0 <1.0.0"
  http: ^1.2.1
  meta: ^1.15.0
  path: ^1.9.0
  platform: ^3.1.5
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  uuid: ^4.4.0
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.8.0
  intl: ">=0.17.0 <0.19.0"
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.7

executables:
  metrics:
