name: dart_code_unused_linter
version: 0.0.1
description: Software analytics tool that helps developers analyse and improve software quality.

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.1.0 <5.14.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.2
  args: ^2.4.2
  collection: ^1.18.0
  crypto: ^3.0.3
  file: ^7.0.0
  glob: ^2.1.2
  html: ">=0.15.0 <1.0.0"
  http: ^1.0.0
  meta: ^1.12.0
  path: ^1.9.0
  platform: ^3.1.4
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  uuid: ^4.3.3
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.7.2
  intl: ">=0.17.0 <0.19.0"
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.2

executables:
  metrics:
